clone_depth: 10
configuration: Release
platform: AnyCPU
environment:
  matrix:
  - job_name: Ubuntu 18
    APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
for:
  - matrix:
      only:
        - job_name: Ubuntu 18
build: off
test_script:
  - sh: source env.sh
