clone_depth: 10
configuration: Release
platform: AnyCPU

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804

init:
  - appveyor version
  - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
  - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
#  - ps: Update-AppveyorBuild -Message "Test $env:INCLUDE_TAGS tag against $env:TEST_IMAGE @ $env:TEST_CLOUD cloud. $env:APPVEYOR_REPO_COMMIT_MESSAGE"

build: off
test_script:
  - sh: |
        echo "0='$0'"
        echo "@='$@'"
        fail_flag=false
        for var in "$@"; do
            if [ "${#var}" -gt 0 ]; then
                echo "There is argument found in current bash session!"
                echo "argument value is '${var}'"
                fail_flag=true
            fi
        done
        if fail_flag; then exit 1; fi

on_failure:
  - sh: sudo journalctl -u appveyor-build-agent.service  --no-pager > buildagent.log
  - appveyor PushArtifact buildagent.log 
