clone_depth: 10
configuration: Release
platform: AnyCPU

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804

init:
  - appveyor version
  - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
  - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
  - ps: Update-AppveyorBuild -Message "Test $env:INCLUDE_TAGS tag against $env:TEST_IMAGE @ $env:TEST_CLOUD cloud. $env:APPVEYOR_REPO_COMMIT_MESSAGE"

build: off
test_script:
  - sh: echo Provide a value to the script... && source env.sh Provided
  - sh: echo Rely on default value in the script ... && source env.sh
