clone_depth: 10
configuration: Release
platform: AnyCPU

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804

init:
  - appveyor version
  - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
  - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
#  - ps: Update-AppveyorBuild -Message "Test $env:INCLUDE_TAGS tag against $env:TEST_IMAGE @ $env:TEST_CLOUD cloud. $env:APPVEYOR_REPO_COMMIT_MESSAGE"

build: off
test_script:
  - sh: echo "0='$0'"
  - sh: echo "@='$@'"
  - sh: shift
  - sh: echo "0='$0'"
  - sh: echo "@='$@'"
  - sh: echo Provide a value to the script... && source env.sh Provided
  - sh: echo Rely on default value in the script ... && source env.sh
  - sh: source env.sh >foo
  - sh: cat foo
  - appveyor PushArtifact foo
  
  - sh: |
        set -x
        source env.sh
  - sh: |
        mv env.sh foo.sh
        source foo.sh
  - sh: chmod a+x foo.sh
  - sh: ./foo.sh
  - sh: bash -x foo.sh
  
  - sh: sudo journalctl -u appveyor-build-agent.service  --no-pager > buildagent.log
  - appveyor PushArtifact buildagent.log 
